Add documentation
suufi/noblox.js pull request #214
Opened 2020-11-01 01:20 UTC by efewqefwfd

Added documentation across the entire library & added missing TypeScript typings. Also added tutorials that still need to be revised/added to.

2020-11-11 00:15 UTC, Neztore requested changes
Preliminary review - I haven't reviewed all the files but I'm going to check over the typings before finishing this.
I may fix some of these issues, or if you could that'd be great. If you object to any, lmk.

2020-11-11 00:15 UTC, Neztore commented on docs/tutorials/Authentication.md
> +Authentication is pretty simple, it's how Roblox knows who you are and what account you're using. Since Roblox uses FunCaptcha and have no official bot system, developers are forced to use account [*
Would be nice to have some explicit language that says that we use an **authentication token** which happens to be stored within cookies. And it links to an authentication session.

2020-11-11 00:15 UTC, Neztore commented on lib/asset/uploadModel.js
> + * @param {Buffer} data - The model data.
Buffer does not match the `uploadItem` method nor the [Typescript typings](https://github.com/suufi/noblox.js/blob/master/typings/index.d.ts#L984) - is it a buffer or a Stream?

2020-11-11 00:15 UTC, Neztore commented on lib/avatar/getCurrentAvatar.js
> +/* @module Avatar */
Is this meant to be here? I note none of the other avatar-related files have a `@module` decorator.

2020-11-11 00:15 UTC, Neztore commented on lib/badges/getAwardedTimestamps.js
> + * @param {Array} badgeIds - The badge's id.
Pluralisation - The badge ids

2020-12-20 23:34 UTC, suufi approved these changes
I've corrected any mistakes I saw and revised it so that it targets the docs/ folder for deployment.

2020-12-20 23:36 UTC, Neztore approved these changes

2020-12-20 23:40 UTC, merged