Update index.js to fix accessing of non-existent property
suufi/noblox.js pull request #218
Opened 2020-11-08 17:19 UTC by unix-system

Fix bad reference that causes warnings when used with TypeScript

This isn't really important, since JS *manages*, but it's nice and will get rid of annoying warnings from my runtime.

The warning was: 

``(node:1572) Warning: Accessing non-existent property 'func' of module exports inside circular dependency``

2020-11-08 17:27 UTC, Neztore commented
This isn't an issue with Typescript. it's an issue with node v14 onwards.
A fix was submitted previously which did exactly what you've done. I tested it, and it didn't fix the issue for me.
However I've now tested your code and it appears to be working.
Closes #195

2020-11-08 22:14 UTC, Neztore commented
Hi, this fails the standardJS test.

2020-11-08 22:15 UTC, unix-system commented
Weird - I guess there is some standard misfitting with node v15, TypeScript and StandardJS...

2020-11-09 06:27 UTC, suufi commented
They used to be included but thank you for reminding me to migrate Travis CI from the legacy service. All PRs are now run against `yarn test` which should hopefully prevent future "Adhere to standard commits."

2020-11-09 06:57 UTC, suufi requested changes

2020-11-09 06:57 UTC, suufi commented on lib/index.js
> +  if (exporter.hasOwnProperty("func")) {
See [standard rules](https://eslint.org/docs/rules/no-prototype-builtins)

2020-12-24 08:49 UTC, suufi approved these changes

2021-01-09 10:24 UTC, merged