Added
suufi/noblox.js pull request #273
Opened 2021-02-08 06:22 UTC by Khristian-Sutherland

Added a new function `getPremium()` that takes a user id, and returns `true` or `false` depending on whether the user with the given userId has premium or not. This uses the following endpoint:
`https://premiumfeatures.roblox.com/v1/users/${userId}/validate-membership`
This endpoint requires the bot to be logged in.
Feel free to user a better name than `getPremium`.

2021-02-09 08:10 UTC, alanbixby commented on lib/user/getPremium.js
> + * @returns {Promise<void>}
Return type should be `Promise<boolean>`.

2021-02-09 08:20 UTC, alanbixby requested changes
Small type error in JSDoc info of the main file, otherwise good first pull request. 😀

---

And as a comment, there was some talk in the Roblox API Discord of merging this into [`getPlayerInfo()`](https://github.com/suufi/noblox.js/blob/master/lib/user/getPlayerInfo.js), but I agree with the consensus that leaving this as an independent method for the time being is ideal due to it's need for authentication.

2021-02-09 08:20 UTC, alanbixby commented on lib/user/getPremium.js
> + * @returns {Promise<void>}
Return type should be `boolean` instead of `void`.
```suggestion
 * @returns {Promise<boolean>}
```

2021-02-10 20:15 UTC, suufi commented
Could you send screenshots of you using this function on premium/non-premium members?

2021-02-10 21:21 UTC, Khristian-Sutherland commented
> Could you send screenshots of you using this function on premium/non-premium members?

Thanks for asking, or I wouldn't have found an issue. It works fine now though.
https://gyazo.com/43d54e21deca72f6ff230622e55cdf51
https://gyazo.com/792382b00d28a94590cf81ce2cc1a1bc

2021-02-17 11:04 UTC, merged